WebAdministrator/Models/MotivoAvaliacao.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebAdministrator.Models
{
    [Table("STT_MOTIVO_AVALIACAO", Schema = "STT_O")]
    public class MotivoAvaliacao
    {
        [Key]
        [Column("CD_MODTIVO_AVALIACAO", TypeName = "NUMBER(9)")]
        [ScaffoldColumn(false)]
        public int Cd_Motivo_Avaliacao { get; set; }

        [Display(Name = "Motivo")]
        [Column("DS_MOTIVO")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Esse campo é obrigatório.")]
        public string Ds_Motivo { get; set; }

        [Display(Name = "TIPO")]
        [Column("TIPO")]
        [Range(typeof(int), "1", "100", ErrorMessage = "Informe um tipo.")]
        public int Tipo { get; set; }

        [Column("DT_CRIACAO", TypeName = "DATE")]
        [ScaffoldColumn(false)]
        public DateTime Dt_Criacao { get; set; }

        [Column("CD_USUARIO_CRIACAO", TypeName = "VARCHAR2(30)")]
        [ScaffoldColumn(false)]
        public string Cd_Usuario_Criacao { get; set; }

        [Column("DT_ATUALIZACAO", TypeName = "DATE")]
        [ScaffoldColumn(false)]
        public DateTime Dt_Atualizacao { get; set; } = DateTime.Now.Date;

        [Column("CD_USUARIO_ATUALIZACAO", TypeName = "VARCHAR2(30)")]
        [ScaffoldColumn(false)]
        public string Cd_Usuario_Atualizacao { get; set; }

        [Column("STATUS")]
        public bool Status { get; set; }

        [NotMapped]
        public int? StatusFilter { get; set; }
    }
}

WebAdministrator/Controllers/MotivoAvaliacaoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Linq;
using WebAdministrator.DAL;
using WebAdministrator.Models;
using X.PagedList;

namespace WebAdministrator.Controllers
{
    [Authorize]
    public class MotivoAvaliacaoController : Controller
    {
        private GenericRepositoryValidation.GenericRepositoryExceptionStatus status;

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create(int id)
        {
            try
            {
                if (id > 0)
                {
                    using DbCon db = new DbCon();
                    using var contexto = new RepositoryGeneric<MotivoAvaliacao>(db, out status);
                    if (status == GenericRepositoryValidation.GenericRepositoryExceptionStatus.Success)
                    {
                        var _motivo = contexto.GetItem(n => n.Cd_Motivo_Avaliacao == id);
                        return View(_motivo);
                    }
                    else
                        throw new Exception($"Erro na conexão de dados Oracle: {status}");
                }
                else
                    return View();
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MotivoAvaliacao motivoAvaliacao)
        {
            if (motivoAvaliacao.Cd_Motivo_Avaliacao == 0)
                ModelState.Remove("Cd_Motivo_Avaliacao");

            try
            {
                if (ModelState.IsValid)
                {
                    using DbCon db = new DbCon();
                    using var contexto = new RepositoryGeneric<MotivoAvaliacao>(db, out status);
                    if (status == GenericRepositoryValidation.GenericRepositoryExceptionStatus.Success)
                    {
                        motivoAvaliacao.Cd_Usuario_Criacao = motivoAvaliacao.Cd_Usuario_Atualizacao = User.Identity.Name ?? "ANONYMOUS";
                        motivoAvaliacao.Dt_Criacao = motivoAvaliacao.Dt_Atualizacao = DateTime.Now.Date;
                        int ret = contexto.Create(motivoAvaliacao);
                        ModelState.Clear();
                        ViewData["retorno"] = ret;
                        return View();
                    }
                    else
                        throw new Exception($"Erro na conexão de dados Oracle: {status}");
                }
                else
                    return View();
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MotivoAvaliacao _motivoAvaliacao)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using DbCon db = new DbCon();
                    using var contexto = new RepositoryGeneric<MotivoAvaliacao>(db, out status);
                    if (status == GenericRepositoryValidation.GenericRepositoryExceptionStatus.Success)
                    {
                        _motivoAvaliacao.Cd_Usuario_Atualizacao= User.Identity.Name ?? "ANONYMOUS";
                        _motivoAvaliacao.Dt_Atualizacao = DateTime.Now.Date;

                        int ret = contexto.Edit(_motivoAvaliacao);
                        ModelState.Clear();
                        ViewData["retorno"] = ret == 1 ? 2 : 0;
                        return View("Create");
                    }
                    else
                        throw new Exception($"Erro na conexão de dados Oracle: {status}");
                }
                else
                    return View("Create", _motivoAvaliacao);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpGet]
        public string GetAutoComplete(string _campo)
        {
            using DbCon db = new DbCon();
            using var contexto = new RepositoryGeneric<MotivoAvaliacao>(db, out status);
            if (status == GenericRepositoryValidation.GenericRepositoryExceptionStatus.Success)
            {
                var consulta = contexto.GetAll(n => n.Ds_Motivo.ToUpper().StartsWith(_campo.ToUpper()));
                var query = consulta.Select(n => new { text = n.Ds_Motivo.ToString(), id = n.Cd_Motivo_Avaliacao.ToString() });

                if (query == null)
                    return null;
                else
                    return JsonConvert.SerializeObject(query, Formatting.None);
            }
            else
            {
                return "";
            }
        }

        [HttpGet]
        [Route("/MotivoAvaliacao/Search/{skip:int}")]
        public PartialViewResult Search(string motivo, int skip = 1)
        {
            try
            {
                MotivoAvaliacao obj = JsonConvert.DeserializeObject<MotivoAvaliacao>(motivo);
                obj.Status = obj.StatusFilter.HasValue && Convert.ToBoolean((int)obj.StatusFilter);

                using DbCon db = new DbCon();
                using var contexto = new RepositoryGeneric<MotivoAvaliacao>(db, out status);

                if (status == GenericRepositoryValidation.GenericRepositoryExceptionStatus.Success)
                {
                    var consulta = contexto.GetAll
                        (
                            x => (x.Ds_Motivo.ToUpper().StartsWith(obj.Ds_Motivo.ToUpper())) && (x.Tipo == (obj.Tipo == 0 ? x.Tipo : obj.Tipo))
                             && (obj.StatusFilter.HasValue ? x.Status == obj.Status : x.Status == x.Status)
                        ).OrderBy(i => i.Ds_Motivo);

                    var query = consulta.ToPagedList(skip, 25);
                    if (query == null)
                        return null;
                    else
                        return PartialView("ListRecord", query);
                }

                return PartialView("ListRecord", status);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}

WebAdministrator/Views/MotivoAvaliacao/Create.cshtml
@model WebAdministrator.Models.MotivoAvaliacao

@{
    ViewData["Title"] = Model == null ? "Cadastrar" : "Atualizar";

    if (Convert.ToInt32(ViewData["retorno"]) > 0)
    {
        <script>
            M.toast({ html: '<i class="material-icons white-text">check_circle</i>&nbsp;Motivo da avaliação @(Convert.ToInt32(ViewData["retorno"]) == 1 ? "cadastrado": "atualizado") com sucesso!', classes: 'blue darken-2 rounded' });
        </script>
    }
}


<h4>@(Model == null ? "Cadastro" : "Edição") de Motivo da Avaliação</h4>
<br />
<div class="row">
    <div class="col s12">
        <form asp-action='@(Model == null ? "Create" : "Edit")'>
            <input asp-for="Cd_Motivo_Avaliacao" type="hidden" />
            <input asp-for="Cd_Usuario_Criacao" type="hidden" />
            <div asp-validation-summary="ModelOnly" class="red-text"></div>
            <div class="input-field">
                <i class="material-icons prefix">mode_edit</i>
                <input asp-for="Ds_Motivo" autocomplete="off" class="autocomplete"/>
                <label asp-for="Ds_Motivo"></label>
                <span asp-validation-for="Ds_Motivo" class="red-text"></span>
            </div>
            <div class="input-field">
                <i class="material-icons prefix">storage</i>
                <select asp-for="Tipo" class="validate">
                    <option value="" disabled selected>Selecione uma opção...</option>
                    <option value="1">Subsídio</option>
                    <option value="2">Subsídio Específico</option>
                    <option value="3">Resumo Fático</option>
                </select>
                <label asp-for="Tipo"></label>
                <span asp-validation-for="Tipo" class="red-text"></span>
            </div>
            <div class="switch">
                Status: &nbsp;
                <label>
                    Inativo
                    <input type="checkbox" asp-for="Status" name="Status" id="Status">
                    <span class="lever"></span>
                    Ativo
                </label>
            </div>
            <br />

            <div class="input-field">
                <button class="btn waves-effect waves-light" type="submit" name="action">
                    <i class="material-icons left">save</i>
                    @(Model == null ? "Adicionar" :"Atualizar") Motivo
                </button>
                <button class="btn waves-effect waves-light" type="button" id="clearFrm" style="display:@(Model != null ? "none" : "");">
                    <i class="material-icons left">clear</i>
                    Limpar
                </button>
            </div>
        </form>
    </div>
</div>
<script>
    document.getElementsByName('Status')[0].checked = Boolean(@(Model == null ? 1 : Convert.ToInt32(Model.Status)));
</script>

WebAdministrator/Views/MotivoAvaliacao/Index.cshtml
@{
    ViewData["Title"] = "Motivo da Avaliação";

}

<h4>Administrar Motivo da Avaliação</h4>

<form>
    <div class="row">

        <div class="input-field col s6">
            @*<i class="material-icons prefix">group</i>*@
            <input id="ds_motivo" type="text">
            <label for="ds_motivo">Motivo</label>
        </div>

        <div class="input-field col s4">
            <select id="tipo">
                <option value="0">Todos</option>
                <option value="1">Subsídio</option>
                <option value="2">Subsídio Específico</option>
                <option value="3">Resumo Fático</option>
            </select>
            <label>Tipo</label>
        </div>
        <div class="input-field col s2">
            <select id="StatusFilter">
                <option value="" selected>Todos</option>
                <option value="1">Ativo</option>
                <option value="0">Inativo</option>
            </select>
            <label>Status</label>
        </div>
    </div>

    <div class="row">
        <div class="col s12">
            <a class="waves-effect waves-light btn-small" id="btnSearch"><i class="material-icons left">search</i>Pesquisar</a>
            <a class="waves-effect waves-light btn-small" id="btnClear"><i class="material-icons left">clear</i>Limpar</a>
            <a asp-controller="MotivoAvaliacao" asp-action="Create" class="waves-effect waves-light btn-small"><i class="material-icons left small">add</i>Novo Motivo</a>
        </div>
    </div>
</form>
<hr>
<footer id="DivRenderData" style="display:none;">
    <partial name="ListRecord" />
</footer>

WebAdministrator/Views/MotivoAvaliacao/ListRecord.cshtml
@model X.PagedList.IPagedList<MotivoAvaliacao>
@using X.PagedList.Mvc.Core
@using X.PagedList.Web.Common

<style>
    tbody {
        display: block;
        max-height: 240px;
        overflow: auto;
    }

        thead, tbody tr {
            display: table;
            width: 100%;
            table-layout: fixed; /* even columns width , fix width of table too*/
        }

    td, th {
        padding: 5px;
        display: table-cell;
        text-align: left;
        vertical-align: middle;
        border-radius: 2px;
        margin: 1px;
    }

    .pagination li a {
        color: #444;
        display: inline-block;
        font-size: 14px;
        padding: 0 10px;
    }

    .totalitemcount {
        font-size: 11px;
        color: slategrey;
        text-align: right;
    }
</style>


@if (Model?.Count() > 0)
{
    <table class="striped">
        <thead>
            <tr>
                <th style="width:100%;">
                    @Html.DisplayNameFor(model => model[0].Ds_Motivo)
                </th>
                <th style="width:180px;">
                    @Html.DisplayNameFor(model => model[0].Tipo)
                </th>
                <th style="width:100px;">
                    @Html.DisplayNameFor(model => model[0].Status)
                </th>
                <th style="width:150px;" class="totalitemcount">Total de Registros: @Model.TotalItemCount</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td style="width:100%;">
                        @Html.DisplayFor(modelItem => item.Ds_Motivo)
                    </td>
                    <td style="width:180px;">
                        @(item.Tipo == 1 ? "Subsídio" : item.Tipo == 2 ? "Subsídio Específico" : "Resumo Fático")
                    </td>
                    <td style="width:100px;">
                        @(item.Status ? "Ativo" : "Inativo")
                    </td>
                    <td style="width:150px;" class="right-align">
                        <a asp-controller="MotivoAvaliacao" asp-action="Create" asp-route-id="@item.Cd_Motivo_Avaliacao" class="waves-effect waves-light btn-small"><i class="material-icons left">edit</i>Editar</a>
                    </td>
                </tr>
            }
        </tbody>
        <tfoot style="padding-top:0px;">
            <tr>
                <td colspan="5" class="center">
                    <input type="hidden" value="@Model.PageCount" id="pageCount" />
                    @Html.PagedListPager(Model, page => null, new PagedListRenderOptions
               {
                   DisplayLinkToIndividualPages = true,
                   DisplayPageCountAndCurrentLocation = false,
                   MaximumPageNumbersToDisplay = 10,
                   LiElementClasses = new string[] { "waves-effect" },
                   PageClasses = new string[] { "btnSearch" },
                   DisplayLinkToNextPage = PagedListDisplayMode.Never,
                   DisplayLinkToPreviousPage = PagedListDisplayMode.Never,
                   DisplayEllipsesWhenNotShowingAllPageNumbers = false,
               })

                </td>
            </tr>

        </tfoot>
    </table>
}
else
{
    <div class="col row z-depth-3 red white-text center-align" style="height: 50px; border: 1px solid; border-radius: 10px; padding:12px 0px 0px 0px;">
        <div class="col s1 left-align"><i class="material-icons white-text">report_problem</i></div>
        <div class="col s11 center">Nenhuma registro foi localizado com o filtro aplicado</div>
    </div>

}

<script>
    $(document).ready(function () {

        $('.pagination').attr('id', 'pageItem');

        var paren = $('.pagination').find('li');

        paren.each(function (index, li) {
            li.id = li.innerText
            li.innerHTML = "<a class='btnSearch'>" + li.innerText + "</a>";
        });

        $('.btnSearch').click(() => {
            var ul = document.getElementById('pageItem');
            ul.onclick = function (event) {
                var target = getEventTarget(event);
                $("#btnSearch").trigger("click", target.innerHTML);
            };
        });
    });

    function getEventTarget(e) {
        e = e || window.event;
        return e.target || e.srcElement;
    }

</script>