WebAdministrator/Models/Usuario.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebAdministrator.Models
{
    [Table("STT_USUARIO", Schema = "STT_O")]
    public class Usuario
    {
        [Key]        
        [Column("CD_USUARIO", TypeName = "NUMBER(9)")]
        public int Cd_Usuario { get; set; }


        [Display(Name = "Nome")]
        [Column("NOME", TypeName = "VARCHAR2(100)")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Informe o nome do usuário.")]
        public string Nome { get; set; }

        [Display(Name = "Login")]
        [Column("LOGIN", TypeName = "VARCHAR2(15)")]
        public string Login { get; set; }

        [Display(Name = "Senha")]
        [Column("PASSWORD ", TypeName = "VARCHAR2(100)")]
        [StringLength(15, ErrorMessage = "Deve conter pelo menos 6 caracteres.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Informe uma senha.")]
        public string Password { get; set; }
        
        [NotMapped]
        [Display(Name = "Confirmar Senha")]
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "As senhas informada não coincidem.")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Informe uma senha.")]
        public string ConfirmPassword { get; set; }

        [Display(Name = "E-mail")]
        [Column("EMAIL", TypeName = "VARCHAR2(100)")]
        [DataType(DataType.EmailAddress, ErrorMessage = "E-mail inválido.")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Informe o e-mail do usuário.")]
        public string Email { get; set; }

        [Column("STATUS")]
        public bool Status { get; set; }

        [Column("DT_CRIACAO", TypeName = "DATE")]
        [ScaffoldColumn(false)]
        public DateTime Dt_Criacao { get; set; }

        [Column("CD_USUARIO_CRIACAO", TypeName = "VARCHAR2(30)")]
        [MaxLength(30)]
        [ScaffoldColumn(false)]
        public string Cd_Usuario_Criacao { get; set; }

        [Column("DT_ATUALIZACAO", TypeName = "DATE")]
        [ScaffoldColumn(false)]
        public DateTime Dt_Atualizacao { get; set; } = DateTime.Now.Date;

        [Column("CD_USUARIO_ATUALIZACAO", TypeName = "VARCHAR2(30)")]
        [MaxLength(30)]
        [ScaffoldColumn(false)]
        public string Cd_Usuario_Atualizacao { get; set; }

        [NotMapped]
        public int? StatusFilter { get; set; }
    }
}

WebAdministrator/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Linq;
using System.Text.RegularExpressions;
using WebAdministrator.DAL;
using WebAdministrator.Models;
using X.PagedList;

namespace WebAdministrator.Controllers
{
    [Authorize]
    public class UsuarioController : Controller
    {
        private GenericRepositoryValidation.GenericRepositoryExceptionStatus status;

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create(int id)
        {
            try
            {
                if (id > 0)
                {
                    using DbCon db = new DbCon();
                    using var contexto = new RepositoryGeneric<Usuario>(db, out status);
                    if (status == GenericRepositoryValidation.GenericRepositoryExceptionStatus.Success)
                    {
                        var _usuario = contexto.GetItem(n => n.Cd_Usuario == id);
                        return View(_usuario);
                    }
                    else
                        throw new Exception($"Erro na conexão de dados Oracle: {status}");
                }
                else
                    return View();
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Usuario _usuario)
        {
            try
            {
                ModelState.Remove("Cd_Usuario");

                if (ModelState.IsValid)
                {
                    using DbCon db = new DbCon();
                    using var contexto = new RepositoryGeneric<Usuario>(db, out status);
                    if (status == GenericRepositoryValidation.GenericRepositoryExceptionStatus.Success)
                    {
                        _usuario.Cd_Usuario_Criacao = _usuario.Cd_Usuario_Atualizacao = User.Identity.Name ?? "ANONYMOUS";
                        _usuario.Dt_Criacao = _usuario.Dt_Atualizacao;

                        _usuario.Password = Util.Utility.Criptografar(_usuario.Password);

                        int ret = contexto.Create(_usuario);
                        ModelState.Clear();
                        ViewData["retorno"] = ret;
                        return View();
                    }
                    else
                        throw new Exception($"Erro na conexão de dados Oracle: {status}");
                }
                return View();
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Usuario _usuario)
        {
            try
            {
                if (string.IsNullOrEmpty(_usuario.Password))
                {
                    ModelState.Remove("Password");
                    ModelState.Remove("ConfirmPassword");
                }

                if (ModelState.IsValid)
                {
                    using DbCon db = new DbCon();
                    using var contexto = new RepositoryGeneric<Usuario>(db, out status);
                    if (status == GenericRepositoryValidation.GenericRepositoryExceptionStatus.Success)
                    {
                        var usuario = contexto.GetItem(n => n.Cd_Usuario == _usuario.Cd_Usuario);
                        usuario.Cd_Usuario_Atualizacao = User.Identity.Name ?? "ANONYMOUS";
                        usuario.Dt_Atualizacao = DateTime.Now.Date;
                        usuario.Status = _usuario.Status;
                        usuario.Email = _usuario.Email;
                        usuario.Login = _usuario.Login;
                        usuario.Nome = _usuario.Nome;
                        usuario.Password = string.IsNullOrWhiteSpace(_usuario.Password) ? usuario.Password : Util.Utility.Criptografar(_usuario.Password);

                        int ret = contexto.Edit(usuario);
                        ModelState.Clear();
                        ViewData["retorno"] = ret == 1 ? 2 : 0;
                        return View("Create");
                    }
                    else
                        throw new Exception($"Erro na conexão de dados Oracle: {status}");
                }
                else
                    return View("Create",_usuario);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpGet]
        public string GetAutoComplete(string _campo)
        {
            using DbCon db = new DbCon();
            using var contexto = new RepositoryGeneric<Usuario>(db, out status);
            if (status == GenericRepositoryValidation.GenericRepositoryExceptionStatus.Success)
            {
                _campo = Regex.Replace(_campo, @"[^0-9$]", string.Empty);
                var consulta = contexto.GetAll(n => n.Email.ToUpper().StartsWith(_campo.ToUpper()));
                var query = consulta.Select(n => new { text = n.Email , id = n.Cd_Usuario.ToString() });

                if (query == null)
                    return null;
                else
                    return JsonConvert.SerializeObject(query, Formatting.None);
            }
            else
            {
                return "";
            }
        }

        [HttpGet]
        [Route("/Usuario/Search/{skip:int}")]
        public PartialViewResult Search(string usuario, int skip = 1)
        {
            try
            {
                Usuario obj = JsonConvert.DeserializeObject<Usuario>(usuario);

                obj.Status = obj.StatusFilter.HasValue && Convert.ToBoolean((int)obj.StatusFilter);

                using DbCon db = new DbCon();
                using var contexto = new RepositoryGeneric<Usuario>(db, out status);

                if (status == GenericRepositoryValidation.GenericRepositoryExceptionStatus.Success)
                {
                    var consulta = contexto.GetAll
                        (
                            x => (x.Nome.ToUpper().StartsWith(obj.Nome.ToUpper()) && x.Login.ToLower().StartsWith(obj.Login.ToLower()) && x.Login.ToLower().StartsWith(obj.Login.ToLower()))
                             && (obj.StatusFilter.HasValue ? x.Status == obj.Status : x.Status == x.Status)
                        ).OrderBy(i => i.Nome);

                    var query = consulta.ToPagedList(skip, 25);
                    if (query == null)
                        return null;
                    else
                        return PartialView("ListRecord", query);
                }

                return PartialView("ListRecord", status);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}

WebAdministrator/Views/Usuario/Create.cshtml
@model WebAdministrator.Models.Usuario

@{
    ViewData["Title"] = Model == null ? "Cadastrar" : "Atualizar";


    if (Convert.ToInt32(ViewData["retorno"]) > 0)
    {
        <script>
            M.toast({ html: '<i class="material-icons white-text">check_circle</i>&nbsp;Usuário @(Convert.ToInt32(ViewData["retorno"]) == 1 ? "cadastrado": "atualizado") com sucesso!', classes: 'blue darken-2 rounded' });
        </script>
    }
}

<h4>@(Model == null ? "Cadastro" : "Edição") de Usuário</h4>
<br />
<form asp-action='@(Model == null ? "Create" : "Edit")'>
    <input asp-for="Cd_Usuario" type="hidden" />
    <input asp-for="Cd_Usuario_Criacao" type="hidden" />
    <div class="row">
        <div asp-validation-summary="ModelOnly" class="red-text"></div>

        <div class="input-field col s4">
            <label asp-for="Nome"></label>
            <input asp-for="Nome" autocomplete="off" />
            <span asp-validation-for="Nome" class="red-text"></span>
        </div>
        <div class="input-field col s4">
            <label asp-for="Email"></label>
            <input asp-for="Email" autocomplete="off" />
            <span asp-validation-for="Email" class="red-text"></span>
        </div>
        <div class="input-field col s4">
            <label asp-for="Login"></label>
            <input asp-for="Login" autocomplete="off" readonly placeholder="login gerado automático"/>
        </div>
    </div>
    <div class="row">
        <div class="input-field col s4">
            <label asp-for="Password"></label>
            <input asp-for="Password" autocomplete="off" value="@(Model != null ? null : "$123Master")" />
            <span asp-validation-for="Password" class="red-text"></span>
        </div>
        <div class="input-field col s4">
            <label asp-for="ConfirmPassword"></label>
            <input asp-for="ConfirmPassword" autocomplete="off" value="@(Model != null ? null : "$123Master")" />
            <span asp-validation-for="ConfirmPassword" class="red-text"></span>
        </div>
        <div class="col s4" style="padding-top:25px;">
            @if (Model == null)
            {
            <div class="chip">
                <i class="material-icons left">lock</i>
                Senha padrão para novos usuários: $123Master
            </div>
            }
        </div>
    </div>
    <div class="row">
        <br />
        <div class="switch">
            Status: &nbsp;
            <label>
                Inativo
                <input type="checkbox" asp-for="Status" name="Status" id="Status">
                <span class="lever"></span>
                Ativo
            </label>
        </div>
        <br />
        <div class="input-field">
            <button class="btn waves-effect waves-light" type="submit" name="action" id="btnSendUsuario">
                <i class="material-icons left">save</i>
                @(Model == null ? "Adicionar" :"Atualizar") Usuário
            </button>
            <button class="btn waves-effect waves-light" type="button" id="clearFrm" style="display:@(Model != null ? "none" : "");">
                <i class="material-icons left">clear</i>
                Limpar
            </button>
        </div>
    </div>
</form>
<script>
    document.getElementsByName('Status')[0].checked = Boolean(@(Model == null ? 1 : Convert.ToInt32(Model.Status)));

    $(document).ready(function () {

        $('#Email').focusout(function () {
            var emailRegex = /^\w+([-+.']\w+)*@@\w+([-.]\w+)*\.\w+([-.]\w+)*$/;

            if (!emailRegex.test($('#Email').val())) {
                M.toast({ html: '<i class="material-icons white-text">highlight_off</i>&nbsp;formato de email inválido', classes: 'red rounded' });
                document.getElementById('btnSendUsuario').disabled = true;
                $('#Login').val(null);
                $('#Email').focus();
            }
            else {

                document.getElementById('btnSendUsuario').disabled = false;
                var _login = $('#Email').val().split('@@')[0];
                $('#Login').val(_login);
            }

        });


        $('#Password').prop('readonly', @(Model == null ? "true" : "false"));
        $('#ConfirmPassword').prop('readonly', @(Model == null ? "true" : "false"));
    });
</script>

WebAdministrator/Views/Usuario/Index.cshtml
@{
    ViewData["Title"] = "Usuários";
}

<h4>Pesquisar Usuários</h4>

<form>
    <div class="row">
       
        <div class="input-field col s6">
            <input id="nome" type="text">
            <label>Nome</label>
        </div>
        <div class="input-field col s3">
            <input id="login" type="text">
            <label>Login</label>
        </div>
        <div class="input-field col s3">
            <select id="StatusFilter">
                <option value="" selected>Todos</option>
                <option value="1">Ativo</option>
                <option value="0">Inativo</option>
            </select>
            <label>Status</label>
        </div>
    </div>
    <div class="row">
        <div class="col s12">
            <a class="waves-effect waves-light btn-small" id="btnSearch"><i class="material-icons left">search</i>Pesquisar</a>
            <a class="waves-effect waves-light btn-small" id="btnClear"><i class="material-icons left">clear</i>Limpar</a>
            <a asp-controller="Usuario" asp-action="Create" class="waves-effect waves-light btn-small"><i class="material-icons left small">add</i>Novo Usuário</a>
        </div>
    </div>
</form>
<hr>
<footer id="DivRenderData" style="display:none;">
    <partial name="ListRecord" />
</footer>

WebAdministrator/Views/Usuario/ListRecord.cshtml
@model X.PagedList.IPagedList<Usuario>
@using X.PagedList.Mvc.Core
@using X.PagedList.Web.Common

<style>
    tbody {
        display: block;
        max-height: 240px;
        overflow: auto;
    }

    thead, tbody tr {
        display: table;
        width: 100%;
        table-layout: fixed; /* even columns width , fix width of table too*/
    }

    td, th {
        padding: 5px;
        display: table-cell;
        text-align: left;
        vertical-align: middle;
        border-radius: 2px;
        margin: 1px;
    }

    .pagination li a {
        color: #444;
        display: inline-block;
        font-size: 14px;
        padding: 0 10px;
    }

    .totalitemcount {
        font-size: 11px;
        color: slategrey;
        text-align: right;
    }
</style>


@if (Model?.Count() > 0)
{
    <table class="striped">
        <thead>
            <tr>
                <th style="width:100%;">
                    @Html.DisplayNameFor(model => model[0].Nome)
                </th>
                <th style="width:150px;">
                    @Html.DisplayNameFor(model => model[0].Login)
                </th>
                <th style="width:300px;">
                    @Html.DisplayNameFor(model => model[0].Email)
                </th>
                <th style="width:150px;">
                    @Html.DisplayNameFor(model => model[0].Status)
                </th>
                
                <th style="width:150px;" class="totalitemcount">Total de Registros: @Model.TotalItemCount</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    
                    <td style="width:100%;">
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    <td style="width:150px;">
                        @Html.DisplayFor(modelItem => item.Login)
                    </td>
                    <td style="width:300px;">
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td style="width:150px;">
                        @(item.Status ? "Ativo" : "Inativo")
                    </td>
                    <td style="width:150px;" class="right-align">
                        <a asp-controller="Usuario" asp-action="Create" asp-route-id="@item.Cd_Usuario" class="waves-effect waves-light btn-small"><i class="material-icons left">edit</i>Editar</a>
                    </td>
                </tr>
            }
        </tbody>
        <tfoot style="padding-top:0px;">
            <tr>
                <td colspan="5" class="center">
                    <input type="hidden" value="@Model.PageCount" id="pageCount" />
                    @Html.PagedListPager(Model, page => null, new PagedListRenderOptions
               {
                   DisplayLinkToIndividualPages = true,
                   DisplayPageCountAndCurrentLocation = false,
                   MaximumPageNumbersToDisplay = 10,
                   LiElementClasses = new string[] { "waves-effect" },
                   PageClasses = new string[] { "btnSearch" },
                   DisplayLinkToNextPage = PagedListDisplayMode.Never,
                   DisplayLinkToPreviousPage = PagedListDisplayMode.Never,
                   DisplayEllipsesWhenNotShowingAllPageNumbers = false,
               })

                </td>
            </tr>

        </tfoot>
    </table>
}
else
{
    <div class="col row z-depth-3 red white-text center-align" style="height: 50px; border: 1px solid; border-radius: 10px; padding:12px 0px 0px 0px;">
        <div class="col s1 left-align"><i class="material-icons white-text">report_problem</i></div>
        <div class="col s11 center">Nenhuma registro foi localizado com o filtro aplicado</div>
    </div>

}

<script>
    $(document).ready(function () {

        $('.pagination').attr('id', 'pageItem');

        var paren = $('.pagination').find('li');

        paren.each(function (index, li) {
            li.id = li.innerText
            li.innerHTML = "<a class='btnSearch'>" + li.innerText + "</a>";
        });

        $('.btnSearch').click(() => {
            var ul = document.getElementById('pageItem');
            ul.onclick = function (event) {
                var target = getEventTarget(event);
                $("#btnSearch").trigger("click", target.innerHTML);
            };
        });
    });

    function getEventTarget(e) {
        e = e || window.event;
        return e.target || e.srcElement;
    }

</script>