WebAdministrator/Models/Pedido.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using X.PagedList;

namespace WebAdministrator.Models
{
    [Table("STT_TIPO_PEDIDO", Schema = "STT_O")]
    public class Pedido
    {
        [Key]
        [Column("CD_TIPO_PEDIDO", TypeName = "NUMBER(9)")]
        [ScaffoldColumn(false)]
        public int Cd_Tipo_Pedido { get; set; }

        [Column("CD_PROCESSO", TypeName = "NUMBER(9)")]
        [ScaffoldColumn(false)]
        public int Cd_Processo { get; set; }

        [Column("DT_CRIACAO", TypeName = "DATE")]
        [ScaffoldColumn(false)]
        public DateTime Dt_Criacao { get; set; }

        [Column("CD_USUARIO_CRIACAO", TypeName = "VARCHAR2(30)")]
        [ScaffoldColumn(false)]
        [StringLength(30)]
        public string Cd_Usuario_Criacao { get; set; }

        [Column("DT_ATUALIZACAO", TypeName = "DATE")]
        [ScaffoldColumn(false)]
        public DateTime Dt_Atualizacao { get; set; } = DateTime.Now.Date;

        [Column("CD_USUARIO_ATUALIZACAO", TypeName = "VARCHAR2(30)")]
        [ScaffoldColumn(false)]
        [StringLength(30)]
        public string Cd_Usuario_Atualizacao { get; set; }

        [Column("DS_TIPO_PEDIDO", TypeName = "VARCHAR2(100)")]
        [Display(Name = "Descrição do Pedido")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Informe uma descrição para o pedido.")]
        public string Ds_Tipo_Pedido { get; set; }

        [Column("STATUS")]
        public bool Status { get; set; }

        [NotMapped]
        public int? StatusFilter { get; set; }
    }
}

WebAdministrator/Controllers/PedidoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Dynamic;
using System.Linq;
using WebAdministrator.DAL;
using WebAdministrator.Models;
using X.PagedList;

namespace WebAdministrator.Controllers
{
    [Authorize]
    public class PedidoController : Controller
    {
        GenericRepositoryValidation.GenericRepositoryExceptionStatus status;

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create(int id)
        {
            try
            {
                if (id > 0)
                {
                    using DbCon db = new DbCon();
                    using var contexto = new RepositoryGeneric<Pedido>(db, out status);
                    if (status == GenericRepositoryValidation.GenericRepositoryExceptionStatus.Success)
                    {
                        var _pedido = contexto.GetItem(n => n.Cd_Tipo_Pedido == id);
                        return View(_pedido);
                    }
                    else
                        throw new Exception($"Erro na conexão de dados Oracle: {status}");
                }
                else
                    return View();
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Pedido _pedido)
        {
            try
            {
                if (_pedido.Cd_Tipo_Pedido == 0)
                    ModelState.Remove("Cd_Tipo_Pedido");

                if (ModelState.IsValid)
                {
                    using DbCon db = new DbCon();
                    using var contexto = new RepositoryGeneric<Pedido>(db, out status);
                    
                    if (status == GenericRepositoryValidation.GenericRepositoryExceptionStatus.Success)
                    {
                        _pedido.Dt_Criacao = _pedido.Dt_Atualizacao;
                        _pedido.Cd_Usuario_Criacao = _pedido.Cd_Usuario_Atualizacao = User.Identity.Name ?? "ANONYMOUS";
                        int ret = contexto.Create(_pedido);
                        ModelState.Clear();
                        ViewData["retorno"] = ret;
                        return View();
                    }
                    else
                        throw new Exception($"Erro na conexão de dados Oracle: {status}");
                }
                else
                {
                    return View();
                }
                 //   return RedirectToAction(nameof(Index));
            }
            catch(Exception ex)
            {

                throw ex;
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public PartialViewResult AddJustificativa(Justificativa justificativa)
        {
            try
             {
                if(justificativa.Cd_Justificativa_Sentenca == 0)
                    ModelState.Remove("Cd_Justificativa_Sentenca");

                if (ModelState.IsValid)
                {
                    using DbCon db = new DbCon();
                    using var contexto = new RepositoryGeneric<Justificativa>(db, out status);

                    if (status == GenericRepositoryValidation.GenericRepositoryExceptionStatus.Success)
                    {
                        if (justificativa.Cd_Justificativa_Sentenca == 0)
                        {
                            justificativa.Dt_Criacao = justificativa.Dt_Atualizacao;
                            justificativa.Cd_Usuario_Criacao = User.Identity.Name ?? "ANONYMOUS";
                            contexto.Create(justificativa);
                        }
                        else
                        {
                            Justificativa _justificativa = contexto.GetItem(x => x.Cd_Justificativa_Sentenca == justificativa.Cd_Justificativa_Sentenca);

                            _justificativa.Status = justificativa.Status;
                            _justificativa.Ds_Justificativa_Sentenca = justificativa.Ds_Justificativa_Sentenca;
                            _justificativa.Cd_Sentenca = justificativa.Cd_Sentenca;
                            _justificativa.Cd_Usuario_Criacao = User.Identity.Name ?? "ANONYMOUS";
                            contexto.Edit(_justificativa);
                        }
                        ModelState.Clear();
                    }
                    return Parecer(justificativa.Cd_Tipo_Pedido);
                }
                else
                {
                    var erros = ModelState.Values.Where(v => v.ValidationState == Microsoft.AspNetCore.Mvc.ModelBinding.ModelValidationState.Invalid).ToList().Select(f =>f.Errors);
                    var lstErro =  erros.Select(y => y.FirstOrDefault());
                    return PartialView("ListParecer",lstErro.ToPagedList());
                }
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Pedido _pedido)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using DbCon db = new DbCon();
                    using var contexto = new RepositoryGeneric<Pedido>(db, out status);

                    if (status == GenericRepositoryValidation.GenericRepositoryExceptionStatus.Success)
                    {
                        _pedido.Dt_Atualizacao = DateTime.Now.Date;
                        _pedido.Cd_Usuario_Atualizacao = User.Identity.Name ?? "ANONYMOUS";
                        int ret = contexto.Edit(_pedido);
                        ModelState.Clear();
                        ViewData["retorno"] = ret == 1 ? 2 : 0;
                        return View("Create");
                    }
                    else
                        throw new Exception($"Erro na conexão de dados Oracle: {status}");
                }
                else
                {
                    return View("Create",_pedido);
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpGet]
        public string GetAutoComplete(string _campo)
        {
            using DbCon db = new DbCon();
            using var contexto = new RepositoryGeneric<Pedido>(db, out status);
            if (status == GenericRepositoryValidation.GenericRepositoryExceptionStatus.Success)
            {
                var consulta = contexto.GetAll(n => n.Ds_Tipo_Pedido.ToUpper().StartsWith(_campo.ToUpper()));
                var query = consulta.Select(n => new { text = n.Ds_Tipo_Pedido.ToString(), id = n.Cd_Processo.ToString() });

                if (query == null)
                    return null;
                else
                    return JsonConvert.SerializeObject(query, Formatting.None);
            }
            else
            {
                return "";
            }
        }

        [HttpGet]
        public string GetAutoCompleteJustificativa(string _campo)
        {
            using DbCon db = new DbCon();
            using var contexto = new RepositoryGeneric<Justificativa>(db, out status);
            if (status == GenericRepositoryValidation.GenericRepositoryExceptionStatus.Success)
            {
                var consulta = contexto.GetAll(n => n.Ds_Justificativa_Sentenca.ToUpper().StartsWith(_campo.ToUpper()));
                var query = consulta.Select(n => new { text = n.Ds_Justificativa_Sentenca.ToString(), id = n.Cd_Sentenca.ToString() });

                if (query == null)
                    return null;
                else
                    return JsonConvert.SerializeObject(query, Formatting.None);
            }
            else
            {
                return "";
            }
        }

        [HttpGet]
        [Route("/Pedido/Search/{skip:int}")]
        public PartialViewResult Search(string pedido, int skip = 1)
        {
            try
            {
                Pedido obj = JsonConvert.DeserializeObject<Pedido>(pedido);
                obj.Status = obj.StatusFilter.HasValue && Convert.ToBoolean((int)obj.StatusFilter);

                using DbCon db = new DbCon();
                using var contexto = new RepositoryGeneric<Pedido>(db, out status);

                if (status == GenericRepositoryValidation.GenericRepositoryExceptionStatus.Success)
                {
                    dynamic Pedido = new ExpandoObject();
                    var consulta = contexto.GetAll
                        (
                            x => (x.Ds_Tipo_Pedido.ToUpper().StartsWith(obj.Ds_Tipo_Pedido.ToUpper()) && (obj.StatusFilter.HasValue ? x.Status == obj.Status : x.Status == x.Status))
                        ).OrderBy(i => i.Ds_Tipo_Pedido);

                    Pedido = consulta.ToPagedList(skip, 25);
                    if (Pedido == null)
                        return null;
                    else
                        return PartialView("ListRecord", Pedido);
                }

                return PartialView("ListRecord", status);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpGet]
        [Route("/Pedido/Parecer/{id:int}")]
        public PartialViewResult Parecer(int id)
        {
            try
            {
                using DbCon db = new DbCon();
                using var contexto = new RepositoryGeneric<Justificativa>(db, out status);

                if (status == GenericRepositoryValidation.GenericRepositoryExceptionStatus.Success)
                {
                    dynamic justificativa = new ExpandoObject();
                    var consulta = contexto.GetAll(x => x.Cd_Tipo_Pedido == id).OrderBy(o => o.Ds_Justificativa_Sentenca);

WebAdministrator/Views/Pedido/Create.cshtml
@model WebAdministrator.Models.Pedido

@{
    ViewData["Title"] = Model == null ? "Cadastrar" : "Atualizar";

    if (Convert.ToInt32(ViewData["retorno"]) > 0)
    {
        <script>
        M.toast({ html: '<i class="material-icons white-text">check_circle</i>&nbsp;Pedido @(Convert.ToInt32(ViewData["retorno"]) == 1 ? "cadastrado": "atualizado") com sucesso!', classes: 'blue darken-2 rounded' });
        </script>
    }
}

<h4>@(Model == null ? "Cadastro" : "Edição") de Pedido</h4>
<br />
<div class="row">
    <div class="col s12">
        <form asp-action='@(Model == null ? "Create" : "Edit")'>
            <input asp-for="Cd_Tipo_Pedido" type="hidden" />
            <input asp-for="Cd_Usuario_Criacao" type="hidden" />
            <div asp-validation-summary="ModelOnly" class="red-text"></div>
            <div class="input-field">
                <i class="material-icons prefix">subject</i>
                <input asp-for="Ds_Tipo_Pedido" autocomplete="off" class="autocomplete" />
                <label asp-for="Ds_Tipo_Pedido"></label>
                <span asp-validation-for="Ds_Tipo_Pedido" class="red-text"></span>
            </div>
            <div class="switch">
                Status: &nbsp;
                <label>
                    Inativo
                    <input type="checkbox" asp-for="Status" name="Status" id="Status">
                    <span class="lever"></span>
                    Ativo
                </label>
            </div>
            <br />
            <div class="input-field">
                <button class="btn waves-effect waves-light" type="submit" name="action">
                    <i class="material-icons left">save</i>
                    @(Model == null ? "Adicionar" :"Atualizar") Pedido
                </button>
                <button class="btn waves-effect waves-light" type="button" id="clearFrm" style="display:@(Model != null ? "none" : "");">
                    <i class="material-icons left">clear</i>
                    Limpar
                </button>
            </div>
        </form>
    </div>
</div>

<script>
    document.getElementsByName('Status')[0].checked = Boolean(@(Model == null ? 1 : Convert.ToInt32(Model.Status)));
</script>

WebAdministrator/Views/Pedido/Index.cshtml
@{
    ViewData["Title"] = "Pedidos";
    
}

<h4>Pesquisar Pedidos</h4>

<form>
    <div class="row">

        <div class="input-field col s10">
            <input id="dspedido" type="text">
            <label>Descrição do Pedido</label>
        </div>

        <div class="input-field col s2">
            <select id="StatusFilter">
                <option value="" selected>Todos</option>
                <option value="1">Ativo</option>
                <option value="0">Inativo</option>
            </select>
            <label>Status</label>
        </div>
    </div>

    <div class="row">
        <div class="col s12">
            <a class="waves-effect waves-light btn-small" id="btnSearch"><i class="material-icons left">search</i>Pesquisar</a>
            <a class="waves-effect waves-light btn-small" id="btnClear"><i class="material-icons left">clear</i>Limpar</a>
            <a asp-controller="Pedido" asp-action="Create" class="waves-effect waves-light btn-small"><i class="material-icons left small">add</i>Novo Pedido</a>
        </div>
    </div>
</form>
<hr>
<footer id="DivRenderData" style="display:none;">
    <partial name="ListRecord" />
</footer>
 

WebAdministrator/Views/Pedido/ListParecer.cshtml
@model X.PagedList.IPagedList<dynamic>

@if (Model?.Count() > 0)
{
    var listItem = new SelectList(WebAdministrator.Util.Utility.GetSelectLists<Sentenca>(x => x.Cd_Sentenca > 0).Select(y => new SelectListItem { Value = y.Cd_Sentenca.ToString(), Text = y.Ds_Sentenca }).AsEnumerable(), "Value", "Text");
    if (Model is X.PagedList.IPagedList<Justificativa>)
    {

        <table class="table" style="margin:auto; width:98%;">
            <thead>
                <tr>
                    <th style="width:100%;">
                        Parecer
                    </th>
                    <th style="width:200px;" class="left-align">
                        Tipo de Sentença
                    </th>
                    <th style="width:120px;" class="left-align">
                        Status
                    </th>
                    <th style="width:150px;" class="totalitemcount">Total de Registros: @Model.TotalItemCount</th>
                </tr>
            </thead>
            <tbody>
                @foreach (Justificativa item in Model)
                {
                    if (item != null)
                    {
                <tr>
                    <td style="width:100%;">
                        @Html.DisplayFor(modelItem => item.Ds_Justificativa_Sentenca)
                    </td>
                    <td style="width:200px;" class="left-align">
                        @Html.DisplayFor(modelItem => listItem.FirstOrDefault(f => f.Value == item.Cd_Sentenca.ToString()).Text)
                    </td>
                    <td style="width:100px;" class="left-align">
                        @(item.Status ? "Ativo" : "Inativo")
                    </td>
                    <td style="width:150px;" class="right-align">
                        <a data="@Json.Serialize(@item).ToString()" onclick="JavaScript: EditParecer(this);" class="btn-small waves-effect waves-light orange darken-3">Editar</a>
                    </td>
                </tr>
                    }
                    else
                    { break; }
                }
            </tbody>
        </table>
    }
    if (Model is X.PagedList.IPagedList<Microsoft.AspNetCore.Mvc.ModelBinding.ModelError>)
    {

        foreach (Microsoft.AspNetCore.Mvc.ModelBinding.ModelError item in Model)
        {
            <label data="0" >@item.ErrorMessage.Trim()</label>
        }
    }
}
else
{
    <div class="col row z-depth-3 red white-text center-align" style="height: 50px; width: 95% ;border: 1px solid; border-radius: 10px; padding:12px 0px 0px 0px;">
        <div class="col s1 left-align"><i class="material-icons white-text">report_problem</i></div>
        <div class="col s11 center">Nenhuma registro foi localizado com o filtro aplicado</div>
    </div>
}

WebAdministrator/Views/Pedido/ListRecord.cshtml
@model X.PagedList.IPagedList<dynamic>
@using X.PagedList.Mvc.Core
@using X.PagedList.Web.Common


<style>
    tbody {
        display: block;
        max-height: 245px;
        overflow: auto;
    }

        thead, tbody tr {
            display: table;
            width: 100%;
            table-layout: fixed; /* even columns width , fix width of table too*/
        }

    td, th {
        padding: 5px;
        display: table-cell;
        text-align: left;
        vertical-align: middle;
        border-radius: 2px;
        margin: 1px;
    }

    .pagination li a {
        color: #444;
        display: inline-block;
        font-size: 14px;
        padding: 0 10px;
    }

    .totalitemcount {
        font-size: 11px;
        color: slategrey;
        text-align: right;
    }

    .modal {
        width: 85% !important;
        overflow: hidden !important;
    }
</style>
@{
    var listItem = new SelectList(WebAdministrator.Util.Utility.GetSelectLists<Sentenca>(x => x.Cd_Sentenca > 0).Select(y => new SelectListItem { Value = y.Cd_Sentenca.ToString(), Text = y.Ds_Sentenca }).AsEnumerable(), "Value", "Text");
}

@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery Xsrf
@functions
{
    public string GetAntiXsrfRequestToken()
    {
        return Xsrf.GetAndStoreTokens(Context).RequestToken;
    }
}
<div id="modalParecer" class="modal modal-fixed-footer">
    <form id="frmParecer">
        <input id="cd_tipo_pedido" name="cd_tipo_pedido" type="hidden" />
        <input id="cd_justificativa_sentenca" name="cd_justificativa_sentenca" type="hidden" />
        <div class="row">
            <div class="input-field col s3 ">
                <select id="cd_sentenca" name="cd_sentenca" asp-items="listItem">
                    <option value="0" disabled selected>Selecione uma opção</option>
                </select>
                <label>Tipo</label>
            </div>
            <div class="input-field col s7">
                <input type="text" class="autocomplete"  id="ds_justificativa_sentenca" name="ds_justificativa_sentenca"/>
                <label>Justificativa</label>
            </div>
            <div class="col s2 input-field">
                <div class="switch">
                    <label>
                        Inativo
                        <input type="checkbox" name="status" id="status">
                        <span class="lever"></span>
                        Ativo
                    </label>
                </div>
            </div>
        </div>
    </form>
    <div id="DivRenderParecer" style="display:none;">
        <partial name="ListParecer" />
    </div>
    <div class="modal-footer">
        <div class="col s9 left">
            <p class="left indigo-text" id="titlePedido"></p>
        </div>
        <div class="col s3 right">
            <a class="waves-effect waves-red btn-small" id="btnAddParecer">Salvar</a>
            <a class="waves-effect waves-light btn-small" id="popUpFrmParecer">Novo</a>
            <a class="modal-close btn-small" id="closeParecer">Fechar</a>
        </div>
    </div>
</div>

@if (Model?.Count() > 0)
{
    if (Model is X.PagedList.IPagedList<Pedido>)
    {

        <table class="striped">
            <thead>
                <tr>
                    <th style="width:100%;">
                        Descrição do Pedido
                    </th>
                    <th style="width:100px;" class="left-align">
                        Status
                    </th>
                    <th style="width:300px;" class="totalitemcount">Total de Registros: @Model.TotalItemCount</th>
                </tr>
            </thead>
            <tbody>
                @foreach (Pedido item in Model)
                {
                    <tr>
                        <td style="width:100%;">
                            @Html.DisplayFor(modelItem => item.Ds_Tipo_Pedido)
                        </td>
                        <td style="width:80px;" class="left-align">
                            @(item.Status ? "Ativo" : "Inativo")
                        </td>
                        <td style="width:300px;" class="right-align">
                            @*<a class="waves-effect waves-light btn modal-trigger" href="#modal1">Modal</a>*@
                            <a class="waves-effect btn-small modal-trigger lime darken-3" onclick="JavaScript: OpenParecer(JSON.stringify({ cd_tipo_pedido:@item.Cd_Tipo_Pedido, ds_tipo_pedido:'@item.Ds_Tipo_Pedido'}));" href="#modalParecer"><i class="material-icons left">chat</i>Parecer</a>
                            <a asp-controller="Pedido" asp-action="Create" asp-route-id="@item.Cd_Tipo_Pedido" class="waves-effect waves-light btn-small"><i class="material-icons left">edit</i>Editar</a>
                        </td>
                    </tr>
                }
            </tbody>
            <tfoot style="padding-top:0px;">
                <tr>
                    <td colspan="10" class="center" style="height:20px;">
                        <input type="hidden" value="@Model.PageCount" id="pageCount" />
                        @Html.PagedListPager(Model, page => null, new PagedListRenderOptions
                   {
                       DisplayLinkToIndividualPages = true,
                       DisplayPageCountAndCurrentLocation = false,
                       MaximumPageNumbersToDisplay = 10,
                       LiElementClasses = new string[] { "waves-effect" },
                       PageClasses = new string[] { "btnSearch" },
                       DisplayLinkToNextPage = PagedListDisplayMode.Never,
                       DisplayLinkToPreviousPage = PagedListDisplayMode.Never,
                       DisplayEllipsesWhenNotShowingAllPageNumbers = false,
                   })

                    </td>
                </tr>
            </tfoot>
        </table>
    }
}
else
{
    <div class="col row z-depth-3 red white-text center-align" style="height: 50px; border: 1px solid; border-radius: 10px; padding:12px 0px 0px 0px;">
        <div class="col s1 left-align"><i class="material-icons white-text">report_problem</i></div>
        <div class="col s11 center">Nenhuma registro foi localizado com o filtro aplicado</div>
    </div>
}


<script>

    $(document).ready(function () {

        $('.pagination').attr('id', 'pageItem');

        var paren = $('.pagination').find('li');

        paren.each(function (index, li) {
            li.id = li.innerText
            li.innerHTML = "<a class='btnSearch'>" + li.innerText + "</a>";
        });

        $('.btnSearch').click(() => {
            var ul = document.getElementById('pageItem');
            ul.onclick = function (event) {
                var target = getEventTarget(event);
                $("#btnSearch").trigger("click", target.innerHTML);
            };
        });


        $('#btnAddParecer').click(() => {

            var obj = $('#frmParecer').serializeArray().reduce(function (json, { name, value }) {
                json[name] = value;
                return json;
            }, {});

            obj.status = obj?.status == 'on';

            $.ajax({
                headers: { "RequestVerificationToken": "@GetAntiXsrfRequestToken()" },
                type: 'POST',
                url: "/Pedido/AddJustificativa/",
                contentType: "application/x-www-form-urlencoded; charset=UTF-8",
                data: obj,
                dataType: 'html',
                success: function (data) {
                    if ($(data).attr('data') == undefined) {
                        $('#frmParecer').trigger('reset');
                        $('#cd_justificativa_sentenca').val(0);
                        $('#cd_tipo_pedido').val(obj.cd_tipo_pedido);
                        $("#DivRenderParecer").empty().html(data);
                        M.toast({ html: '<i class="material-icons white-text">check_circle</i>&nbsp;Parecer resgistrado com sucesso!', classes: 'blue darken-2 rounded' });
                    }
                    else {
                        var er = $(data).text().trim().split('\n');
                        if (er.length > 0) {
                            var html = '<ul>';
                            er.forEach(function (n) {
                                html += '<li><i class="Tiny material-icons white-text">chevron_right</i >&nbsp;' + n.trim() + '</li>'
                            });
                            html += '</ul>';

                            M.toast({ html:  html, classes: 'purple darken-1 rounded' });
                        }
                    }
                },
                error: function () {
                    $("#DivRenderParecer").empty().html('Ocorreu um erro ao tentar registrar o parecer do pedido');
                }
            });
        });


        $('#closeParecer').click(() => {
            $('#frmParecer').trigger("reset");
        });

        $('#popUpFrmParecer').click(() => {
            var cd_tipo_pedido = $('#cd_tipo_pedido').val();
            $('#frmParecer').trigger("reset");
            $("#status").prop("checked", true);
            $('#cd_tipo_pedido').val(cd_tipo_pedido);
        });


        $('.autocomplete').on('input', function () {

            let filter = $('.autocomplete').val();

            if (filter.length < 3)
                return;

            var tipo = '/' + location.pathname.split('/')[1] + '/GetAutoCompleteJustificativa';
            jQuery.ajax({
                type: 'Get',
                url: tipo,
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                data: { _campo: filter }
            })
                .done(function (dataComplete) {
                    var dataCountry = {};
                    dataComplete.forEach(function (v) {
                        dataCountry[v.text] = null;
                    });

                    $('input.autocomplete').autocomplete({
                        data: dataCountry
                    });

                    $('input.autocomplete').autocomplete('open')

                })
                .fail(function () {
                    M.toast({ html: '<pre><i class="material-icons white-text">report</i> ERRO: AUTO-COMPLETE!<p>Ocorreu uma falha na busca de valores do auto-complete.</p></pre>', classes: 'gray darken-3 rounded' });
                });
        });

    });

    function getEventTarget(e) {
        e = e || window.event;
        return e.target || e.srcElement;
    }

    function OpenParecer(obj) {
        var objPedido = JSON.parse(decodeURIComponent(obj));
        $('#titlePedido').empty().html('<b>PEDIDO:<b/> ' + objPedido.ds_tipo_pedido);
        $('#cd_tipo_pedido').val(objPedido.cd_tipo_pedido);

        $("#status").prop("checked", true);

        $('select').formSelect();
        $('.modal').modal({
            dismissible: false,
            onOpenStart: function () {
                $('#DivRenderParecer').css("display", "");
                jQuery.ajax({
                    type: 'Get',
                    url: '/Pedido/Parecer/' + objPedido.cd_tipo_pedido,
                    contentType: "application/json; charset=utf-8",
                    dataType: "html"
                })
                    .done(function (data) {
                        $("#DivRenderParecer").empty().html(data);

                    })
                    .fail(function (data) {
                        $("#DivRenderParecer").empty().html(data.responseText);
                    });
            }
        });
    }

    function EditParecer(obj) {
        var item = $(obj).attr('data');
        var objeto = JSON.parse(item);
        $('#cd_sentenca').find('option[value=' + objeto.cd_sentenca + ']').prop('selected', true);
        $('select').formSelect();

        $('#ds_justificativa_sentenca').val(objeto.ds_justificativa_sentenca);
        $('#cd_justificativa_sentenca').val(objeto.cd_justificativa_sentenca);
        $('#status').prop('checked', objeto.status);
        $('#ds_justificativa_sentenca').focus();
    }

</script>