WebAdministrator/Controllers/CalendarioController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Linq;
using WebAdministrator.DAL;
using WebAdministrator.Models;
using X.PagedList;

namespace WebAdministrator.Controllers
{
    [Authorize]
    public class CalendarioController : Controller
    {
        private GenericRepositoryValidation.GenericRepositoryExceptionStatus status;
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create(int id)
        {
            try
            {
                if (id > 0)
                {
                    using DbCon db = new DbCon();
                    using var contexto = new RepositoryGeneric<CalendarioAjustavel>(db, out status);
                    if (status == GenericRepositoryValidation.GenericRepositoryExceptionStatus.Success)
                    {
                        var _calendario = contexto.GetItem(n => n.Cd_Calendario == id);
                        return View(_calendario);
                    }
                    else
                        throw new Exception($"Erro na conexão de dados Oracle: {status}");
                }
                else
                    return View();
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CalendarioAjustavel calendarioAjustavel)
        {
            try
            {
                ModelState.Remove("Cd_Calendario");

                if (ModelState.IsValid)
                {
                    using DbCon db = new DbCon();
                    using var contexto = new RepositoryGeneric<CalendarioAjustavel>(db, out status);
                    if (status == GenericRepositoryValidation.GenericRepositoryExceptionStatus.Success)
                    {
                        calendarioAjustavel.Cd_Usuario_Criacao = calendarioAjustavel.Cd_Usuario_Atualizacao = User.Identity.Name ?? "ANONYMOUS";
                        calendarioAjustavel.Dt_Criacao = calendarioAjustavel.Dt_Atualizacao;
                        int ret = contexto.Create(calendarioAjustavel);
                        ModelState.Clear();
                        ViewData["retorno"] = ret;
                        return View();
                    }
                    else
                        throw new Exception($"Erro na conexão de dados Oracle: {status}");
                }
                else
                    return View();
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CalendarioAjustavel calendarioAjustavel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using DbCon db = new DbCon();
                    using var contexto = new RepositoryGeneric<CalendarioAjustavel>(db, out status);
                    if (status == GenericRepositoryValidation.GenericRepositoryExceptionStatus.Success)
                    {
                        calendarioAjustavel.Cd_Usuario_Atualizacao = User.Identity.Name ?? "ANONYMOUS";

                        int ret = contexto.Edit(calendarioAjustavel);
                        ModelState.Clear();
                        ViewData["retorno"] = ret == 1 ? 2 : 0;
                        return View("Create");
                    }
                    else
                        throw new Exception($"Erro na conexão de dados Oracle: {status}");
                }
                else
                    return View("Create", calendarioAjustavel);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpGet]
        [Route("/Calendario/Search/{skip:int}")]
        public PartialViewResult Search(string calendario, int skip = 1)
        {
            try
            {
                CalendarioAjustavel obj = JsonConvert.DeserializeObject<CalendarioAjustavel>(calendario);
                obj.Status = obj.StatusFilter.HasValue && Convert.ToBoolean((int)obj.StatusFilter);

                using DbCon db = new DbCon();
                using var contexto = new RepositoryGeneric<CalendarioAjustavel>(db, out status);

                if (status == GenericRepositoryValidation.GenericRepositoryExceptionStatus.Success)
                {
                    var consulta = contexto.GetAll
                        (
                            x => (x.Ds_Titulo_Data.ToUpper().StartsWith(obj.Ds_Titulo_Data.ToUpper()))
                                && (x.Dt_Nacional.StartsWith(obj.Dt_Nacional))
                                && (x.Sg_Uf == (string.IsNullOrWhiteSpace(obj.Sg_Uf) ? x.Sg_Uf: obj.Sg_Uf))
                                && (obj.StatusFilter.HasValue ? x.Status == obj.Status : x.Status == x.Status)
                        ).OrderBy(i => i.Ds_Titulo_Data);

                    var query = consulta.ToPagedList(skip, 25);
                    if (query == null)
                        return null;
                    else
                        return PartialView("ListRecord", query);
                }

                return PartialView("ListRecord", status);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}

WebAdministrator/Views/Calendario/Create.cshtml
@model WebAdministrator.Models.CalendarioAjustavel

@{

    ViewData["Title"] = Model == null ? "Cadastrar" : "Atualizar";

    if (Convert.ToInt32(ViewData["retorno"]) > 0)
    {
        <script>
            M.toast({ html: '<i class="material-icons white-text">check_circle</i>&nbsp;Data @(Convert.ToInt32(ViewData["retorno"]) == 1 ? "cadastrada": "atualizada") com sucesso!', classes: 'blue darken-2 rounded' });
        </script>
    }
}

<h4>@(Model == null ? "Cadastro" : "Edição") de Datas</h4>
<br />
<form asp-action='@(Model == null ? "Create" : "Edit")'>
    <div asp-validation-summary="ModelOnly" class="red-text"></div>
    <input asp-for="Cd_Calendario" type="hidden" />
    <input asp-for="Cd_Usuario_Criacao" type="hidden" />
    <div class="row">

        <div class="input-field col s2">
            <i class="material-icons prefix">date_range</i>
            <input asp-for="Dt_Nacional" class="datepicker" autocomplete="off" />
            <label asp-for="Dt_Nacional"></label>
            <span asp-validation-for="Dt_Nacional" class="red-text"></span>
        </div>

        <div class="input-field col s3">
            <i class="material-icons prefix">room</i>
            <select asp-for="Sg_Uf" id="Sigla" asp-items="@WebAdministrator.Util.Utility.GetSigla()">
                <option value="NN">Nacional</option>
            </select>
            <label asp-for="Sg_Uf"></label>
            <span asp-validation-for="Sg_Uf" class="red-text"></span>
        </div>
        <div class="input-field col s7">
            <i class="material-icons prefix">edit</i>
            <input asp-for="Ds_Titulo_Data" />
            <label asp-for="Ds_Titulo_Data"></label>
            <span asp-validation-for="Ds_Titulo_Data" class="red-text"></span>
            <span class="new badge" id="titleFeriado" style="display:none;" data-badge-caption=""></span>
        </div>
    </div>
    <div class="row">
        <div class="switch col s12">
            Status: &nbsp;
            <label>
                Inativo
                <input type="checkbox" asp-for="Status" name="Status" id="Status">
                <span class="lever"></span>
                Ativo
            </label>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col s12">
            <button class="btn waves-effect waves-light" type="submit" name="action">
                <i class="material-icons left">save</i>
                @(Model == null ? "Adicionar" :"Atualizar") Data
            </button>
            <button class="btn waves-effect waves-light" type="button" id="clearFrmCalendar" style="display:@(Model != null ? "none" : "");">
                <i class="material-icons left">clear</i>
                Limpar
            </button>
        </div>
    </div>
</form>
<script>
    document.getElementsByName('Status')[0].checked = Boolean(@(Model == null ? 1 : Convert.ToInt32(Model.Status)));

    $(document).ready(function () {

        $('.datepicker').datepicker({
            format: 'dd/mm/yyyy',
            disableWeekends: false,
            autoClose: true,
            i18n: {
                months: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
                monthsShort: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],
                weekdays: ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sabádo'],
                weekdaysShort: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sab'],
                weekdaysAbbrev: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S'],
                today: 'Hoje',
                clear: 'Limpar',
                cancel: 'Sair',
                done: 'Confirmar',
                labelMonthNext: 'Próximo mês',
                labelMonthPrev: 'Mês anterior',
                labelMonthSelect: 'Selecione um mês',
                labelYearSelect: 'Selecione um ano',
                selectMonths: true,
                selectYears: 15,
            },
            onSelect: function (event) {
                let dataSelected = new Date(event);
                $.getJSON("../js/feriadosNacional.json", function (data) {

                    var listItems = data.filter(s => s.data == dataSelected.getFullYear().toString());
                    if (listItems.length > 0) {
                        let detalhes = listItems[0].itens.filter(s => s.date == dataSelected.toJSON().substring(0, 10));

                        if (detalhes.length > 0) {
                            var html = '<ul>';
                            html += '<li><i class="Tiny material-icons white-text">chevron_right</i >&nbsp;Feriado: ' + detalhes[0].name + '</li>'
                            html += '<li><i class="Tiny material-icons white-text">chevron_right</i >&nbsp;Tipo: ' + detalhes[0].type + '</li>'
                            html += '<li><i class="Tiny material-icons white-text">chevron_right</i >&nbsp;Nivel: ' + detalhes[0].level + '</li>'
                            html += '</ul>';

                            M.toast({ html: html, classes: 'blue darken-3 rounded' });
                            $('#titleFeriado').empty().html('FERIADO: ' + detalhes[0].name);
                            $('#Ds_Titulo_Data').val(detalhes[0].name);
                            $('#titleFeriado').show();
                            $('#Ds_Titulo_Data').focus();
                        }
                        else {
                            $('#Ds_Titulo_Data').val(null);
                            $('#titleFeriado').hide();
                            $('#Ds_Titulo_Data').focus();
                        }
                    }
                })
            }
        });

        $('#clearFrmCalendar').click(() => {
            $('form').trigger("reset");
            $("#Status").prop("checked", true);
            $('#titleFeriado').hide();
        });
    });
</script>

WebAdministrator/Views/Calendario/Index.cshtml
@{
    ViewData["Title"] = "Calendário";
}

<h4>Pesquisar Datas</h4>
<form>
    <div class="row">
        <div class="input-field col s2">
            <input type="text" id="dt_nacional" autocomplete="off" />
            <label>Data</label>
        </div>
        <div class="input-field col s3">
            <select id="sg_uf" asp-items="@WebAdministrator.Util.Utility.GetSigla()">
                <option value="">Todos</option>
                <option value="NN">Nacional</option>
            </select>
            
            <label>UF-Estado</label>
        </div>
        <div class="input-field col s5">
            <input type="text" id="ds_titulo_data" autocomplete="off" />
            <label>Descrição</label>
        </div>
        <div class="input-field col s2">
            <select id="StatusFilter">
                <option value="" selected>Todos</option>
                <option value="1">Ativo</option>
                <option value="0">Inativo</option>
            </select>
            <label>Status</label>
        </div>
    </div>
    <div class="row">
        <div class="col s12">
            <a class="waves-effect waves-light btn-small" id="btnSearch"><i class="material-icons left">search</i>Pesquisar</a>
            <a class="waves-effect waves-light btn-small" id="btnClear"><i class="material-icons left">clear</i>Limpar</a>
            <a asp-controller="Calendario" asp-action="Create" class="waves-effect waves-light btn-small"><i class="material-icons left small">add</i>Nova Data</a>
        </div>
    </div>

</form>
<hr>
<footer id="DivRenderData" style="display:none;">
    <partial name="ListRecord" />
</footer>

<script>
    $(document).ready(function () {
        $("#dt_nacional").mask("99/99/9999");
    });
</script>

WebAdministrator/Views/Calendario/ListRecord.cshtml
@model X.PagedList.IPagedList<CalendarioAjustavel>
@using X.PagedList.Mvc.Core
@using X.PagedList.Web.Common

<style>
    tbody {
        display: block;
        max-height: 240px;
        overflow: auto;
    }

        thead, tbody tr {
            display: table;
            width: 100%;
            table-layout: fixed; /* even columns width , fix width of table too*/
        }

    td, th {
        padding: 5px;
        display: table-cell;
        text-align: left;
        vertical-align: middle;
        border-radius: 2px;
        margin: 1px;
    }

    .pagination li a {
        color: #444;
        display: inline-block;
        font-size: 14px;
        padding: 0 10px;
    }

    .totalitemcount {
        font-size: 11px;
        color: slategrey;
        text-align: right;
    }
</style>

@if (Model?.Count() > 0)
{
    <table class="striped">
        <thead>
            <tr>
                <th style="width:100px;">
                    @Html.DisplayNameFor(model => model[0].Dt_Nacional)
                </th>
                <th style="width:100px;">
                    @Html.DisplayNameFor(model => model[0].Sg_Uf)
                </th>
                <th style="width:100%;" class="truncate">
                    @Html.DisplayNameFor(model => model[0].Ds_Titulo_Data)
                </th>
                <th style="width:100px;">
                    @Html.DisplayNameFor(model => model[0].Status)
                </th>
                <th style="width:150px;" class="totalitemcount">Total de Registros: @Model.TotalItemCount</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td style="width:100px;">
                        @Html.DisplayFor(modelItem => item.Dt_Nacional)
                    </td>
                    <td style="width:100px;">
                        @Html.DisplayFor(modelItem => item.Sg_Uf)
                    </td>
                    <td style="width:100%;">
                        @Html.DisplayFor(modelItem => item.Ds_Titulo_Data)
                    </td>
                    <td style="width:100px;">
                        @(item.Status ? "Ativo" : "Inativo")
                    </td>
                    <td style="width:150px;" class="right-align">
                        <a asp-controller="Calendario" asp-action="Create" asp-route-id="@item.Cd_Calendario" class="waves-effect waves-light btn-small"><i class="material-icons left">edit</i>Editar</a>
                    </td>
                </tr>
            }
        </tbody>
        <tfoot style="padding-top:0px;">
            <tr>
                <td colspan="5" class="center">
                    <input type="hidden" value="@Model.PageCount" id="pageCount" />
                    @Html.PagedListPager(Model, page => null, new PagedListRenderOptions
               {
                   DisplayLinkToIndividualPages = true,
                   DisplayPageCountAndCurrentLocation = false,
                   MaximumPageNumbersToDisplay = 10,
                   LiElementClasses = new string[] { "waves-effect" },
                   PageClasses = new string[] { "btnSearch" },
                   DisplayLinkToNextPage = PagedListDisplayMode.Never,
                   DisplayLinkToPreviousPage = PagedListDisplayMode.Never,
                   DisplayEllipsesWhenNotShowingAllPageNumbers = false,
               })
                </td>
            </tr>

        </tfoot>
    </table>
}
else
{
    <div class="col row z-depth-3 red white-text center-align" style="height: 50px; border: 1px solid; border-radius: 10px; padding:12px 0px 0px 0px;">
        <div class="col s1 left-align"><i class="material-icons white-text">report_problem</i></div>
        <div class="col s11 center">Nenhuma registro foi localizado com o filtro aplicado</div>
    </div>

}
<script>
    $(document).ready(function () {

        $('.pagination').attr('id', 'pageItem');

        var paren = $('.pagination').find('li');

        paren.each(function (index, li) {
            li.id = li.innerText
            li.innerHTML = "<a class='btnSearch'>" + li.innerText + "</a>";
        });

        $('.btnSearch').click(() => {
            var ul = document.getElementById('pageItem');
            ul.onclick = function (event) {
                var target = getEventTarget(event);
                $("#btnSearch").trigger("click", target.innerHTML);
            };
        });
    });

    function getEventTarget(e) {
        e = e || window.event;
        return e.target || e.srcElement;
    }

</script>